version: '3.4'

services:

  config-server:
    image: config-server
    ports:
      - "8888:8888"
    networks:
      - currency-network

  currency-exchange:
    image: currency-exchange
    ports:
      - "8001:8001"
    networks:
      - currency-network
    depends_on:
      - config-server
      - eureka-server
    environment:
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver
      - eureka.client.service-url.default-zone=http://localhost:8761/eureka

  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network:

